name: charging_station_app
description: "Ứng dụng quản lý trạm sạc điện"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4

  # MQTT
  mqtt_client: ^10.2.0

  # QR Code Scanner - Thay thế bằng mobile_scanner mới hơn
  mobile_scanner: ^3.5.6

  # State Management
  provider: ^6.1.2

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Utils
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
